datasources:
- name: 'influxdb-telegraf'
  type: 'influxdb'
  access: 'proxy'
  is_default: true
  editable: true
  version: 1
  database: telegraf
  user: admin
  password: password
  url: http://influxdb.service.consul:8086